# Changes here will be overwritten by Copier
_commit: 3a223c6
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Airflow DAG generation from cron syntax
project_name: airflow-crontab
python_version_primary: '3.11'
team: the airflow-crontab authors
